### ISSUE TITLE
Describe link to DK Core and IPA

### ISSUE THREAD

**Issue by jkiddo** [hl7dk/dk-smart#4]

**Comment by jkiddo** [comment]
@AsgerSDSArkitekt can I request you review this section https://build.fhir.org/ig/hl7dk/dk-smart/branches/master/index.html#i-still-dont-follow---why-do-we-need-this - hopefully it brings the needed explanation.

**Comment by AsgerSDSArkitekt** [comment]
@jkiddo : I believe the sections 1.3 and 1.4 improves the IG and makes it more understandable, why that IG is actually needed. I remember, than Christian Gasser fra Lakeside originally had similar "confusion comments" like mine, so maybe also send him a link to the new improved version for more review eyes.

**Comment by jkiddo** [comment]
@christiangasser-lakeside will you have a look as well?

**Comment by jkiddo** [comment]
@christiangasser-lakeside ping?

**Comment by christiangasser-lakeside** [comment]
Yes, the updated section definitely make the IG more understandable :-). Minor detail: The two web-addresses at the end of section 1.4 should be links, so the reader doesn't have to do copy/paste to access the sites.
